# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: ci

on:
  workflow_dispatch

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        python -m pip install --upgrade pip
        pip install git+https://github.com/nathanrooy/PFOIL
    - name: Test with unittest
      run: python -m unittest tests/test_main.py
    - name: Submit to codecov
      if: ${{ matrix.python-version == '3.10' }}
      run: |
        pip install coverage
        coverage run -m unittest tests/test_main.py 
        bash <(curl -s https://codecov.io/bash)
